// [!output PROJECT_NAME].idl 
import "oaidl.idl";
import "ocidl.idl";

[
	uuid([!output LIBID_REGISTRY_FORMAT]),
	version(1.0),
	helpstring("[!output LIB_NAME] 1.0 Type Library")
]
library [!output LIB_NAME]Lib
{
	importlib("stdole2.tlb");

	[
		uuid([!output CONNECT_REGISTRY_FORMAT]),
		helpstring("ConnectProxy Class")
	]
	coclass ConnectProxy
	{
		[default] interface IUnknown;
	};

};
















