//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOutlook2007Addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestOutlook2007Addin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] CustomFormRegion_1_OFS {
            get {
                object obj = ResourceManager.GetObject("CustomFormRegion_1_OFS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        ///	&lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        ///	&lt;formRegionName&gt;FR#1&lt;/formRegionName&gt;
        ///	&lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        ///	&lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        ///	&lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        ///	&lt;icons&gt;
        ///		&lt;page&gt;addin&lt;/page&gt;
        ///	&lt;/icons&gt;
        ///&lt;/FormRegion&gt;.
        /// </summary>
        internal static string CustomFormRegion_1_XML {
            get {
                return ResourceManager.GetString("CustomFormRegion_1_XML", resourceCulture);
            }
        }
        
        internal static byte[] CustomFormRegion_2_OFS {
            get {
                object obj = ResourceManager.GetObject("CustomFormRegion_2_OFS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        ///	&lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        ///	&lt;formRegionName&gt;FR#2&lt;/formRegionName&gt;
        ///	&lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        ///	&lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        ///	&lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        ///	&lt;icons&gt;
        ///		&lt;page&gt;addin&lt;/page&gt;
        ///	&lt;/icons&gt;
        ///&lt;/FormRegion&gt;.
        /// </summary>
        internal static string CustomFormRegion_2_XML {
            get {
                return ResourceManager.GetString("CustomFormRegion_2_XML", resourceCulture);
            }
        }
        
        internal static byte[] CustomFormRegion_3_OFS {
            get {
                object obj = ResourceManager.GetObject("CustomFormRegion_3_OFS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        ///	&lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        ///	&lt;formRegionName&gt;FR#3&lt;/formRegionName&gt;
        ///	&lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        ///	&lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        ///	&lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        ///	&lt;icons&gt;
        ///		&lt;page&gt;addin&lt;/page&gt;
        ///	&lt;/icons&gt;
        ///&lt;/FormRegion&gt;.
        /// </summary>
        internal static string CustomFormRegion_3_XML {
            get {
                return ResourceManager.GetString("CustomFormRegion_3_XML", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabAddIns&quot;&gt;
        ///        &lt;group id=&quot;MyGroup&quot; label=&quot;TestAddin&quot;&gt;
        ///          &lt;toggleButton id=&quot;toggleTaskPane&quot; 
        ///                        label=&quot;TaskPane&quot;
        ///                        imageMso=&quot;ControlLayoutStacked&quot; 
        ///                        size=&quot;large&quot; 
        ///                        onAction=&quot;OnToggleTaskPane&quot; /&gt;
        ///        &lt;/group&gt;
        ///      &lt;/tab&gt;
        ///    &lt;/tabs&gt;
        ///  &lt;/ribbon&gt;
        ///&lt;/customUI&gt;
        ///.
        /// </summary>
        internal static string RibbonX {
            get {
                return ResourceManager.GetString("RibbonX", resourceCulture);
            }
        }
    }
}
